# site settings
title: Better Way Pest Control
email: bbodine1@gmail.com
description: >-
  Pest Control Services for Hartselle, Decatur, Athens, Madison.
  We have the best pest solutions and the best prices to protect the things
  you love from pests.
reviewlimit: 5
gtm-id: MR2CTVP
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# General data
logo-dark: /img/main-logo-dark.png
logo-light: /img/main-logo-light.png
street: 209 Sparkman St SW
city: Hartselle
state: AL
zipcode: 35640
phone: '(256) 580-6181'
service-area: 'North Alabama including Hartselle, Decatur, Madison, Athens, Moulton, and Cullman'

# Social links
facebook: https://www.facebook.com/BetterWayPestControl/
google: https://goo.gl/maps/c3yoeyEDwTn

# Work Hours
hours:
  sun: Closed
  mon: 7am - 6pm
  tue: 7am - 6pm
  wed: 7am - 6pm
  thur: 7am - 6pm
  fri: 7am - 6pm
  sat: 7am - 6pm

# Facebook Share Meta
share-website: https://betterwaypestcontrol.com
share-title: Better Pest Control for North Alabama
share-description: >-
  Our company strives to provide our customers with a great
  service at an affordable price, while protecting your home
  and family from unwanted pests.
share-image: share.jpg

# Navigation
nav:
  - title: Home
    url: /
    subpages:

  - title: About
    url: /about
    subpages:

  - title: Services
    url: /services
    subpages:
      - title: Residential & Commercial Pest Control
        url: /services/residential-commercial
      - title: Mosquito Control
        url: /services/mosquito
      - title: Rodent Control
        url: /services/rodents

  - title: Payments
    url: /payments
    subpages:


# build settings
source: src
destination: dist
markdown: kramdown

plugins:
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 2 versions
sass:
  style: compressed
  load_paths:
    - _sass
    - ../node_modules

collections:
  pages:
    output: true
    permalink: /:path
  reviews:
    output: false
    
# Include
# include:
#   - _pages
#   - _reviews

# Exclude
# exclude:
#   - 'package.json'
#   - 'Gemfile'
#   - '*.gemspec'
#   - '*.lock'
