# site settings
title: Jekyll Starter Site
email: bbodine1@gmail.com
description: >-
  A Starter Jekyll Website using Scss and Bootstrap 4,
  and this is a multi-line variable for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Brad Bodine

# Facebook Share Meta
share-website : https://mywebsite.com
share-title: This is the title of the share
share-description: >-
  This is the description of the share. It should be a bit
  longer. It can be several sentences.
share-image: share.jpg




# build settings
source: src
destination: dist
markdown: kramdown

plugins:
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 2 versions
sass:
  style: compressed
  load_paths:
    - _sass
    - ../node_modules

collections:
  pages:
    output: true
    permalink: /:path
    
# Include
include:
  - _pages

# Exclude
# exclude:
#   - 'package.json'
#   - 'Gemfile'
#   - '*.gemspec'
#   - '*.lock'
