# site settings
title: Better Way Pest Control
email: betterwaypc@gmail.com
email-cc: bbodine1@gmail.com
reviewlimit: 5
gtm-id: MR2CTVP
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# General data
logo-dark: /img/main-logo-dark.png
logo-light: /img/main-logo-light.png
street: 209 Sparkman St SW
city: Hartselle
state: AL
zipcode: 35640
phone: '(256) 580-6181'
service-area: 'North Alabama including Hartselle, Decatur, Madison, Athens, and Moulton'


# Social links
facebook: https://www.facebook.com/BetterWayPestControl/
google: https://goo.gl/maps/c3yoeyEDwTn
yelp: https://www.yelp.com/biz/better-way-pest-control-hartselle


# Work Hours
work-hours:
  - day: Sunday
    hours: Closed
  - day: Monday
    hours: 7am - 6pm
  - day: Tuesday
    hours: 7am - 6pm
  - day: Wednesday
    hours: 7am - 6pm
  - day: Thursday
    hours: 7am - 6pm
  - day: Friday
    hours: 7am - 6pm
  - day: Saturday
    hours: 7am - 6pm


# Navigation
nav:
  - title: Home
    url: /
    subpages:
  - title: About
    url: /about
    subpages:
  - title: Services
    url: /services
    subpages:
      - title: Residential & Commercial Pest Control
        url: /services/residential-commercial-pest-control
      - title: Mosquito Control
        url: /services/mosquito-control
      - title: Rodent Control
        url: /services/rodent-control
      - title: Brown Recluse Control
        url: /services/brown-recluse-control
  - title: Payments
    url: /payments
    subpages:

      
# Service Area Navigation
service-area-pages: true
nav2:
  - title: Decatur
    url: /decatur-alabama
  - title: Hartselle
    url: /hartselle-alabama
  - title: Moulton
    url: /moulton-alabama
  - title: Athens
    url: /athens-alabama
  - title: Madison
    url: /madison-alabama
  - title: Huntsville
    url: /huntsville-alabama


# PayPal settings
paypal-email: israel@betterwaypestcontrol.com
paypal-amount-onform: true
paypal-allow-cancel: false
paypal-sandbox: false
paypal-sandbox-email: bbodine1+merchant@gmail.com


# build settings
source: src
destination: dist
markdown: kramdown

plugins:
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-seo-tag

autoprefixer:
  browsers:
    - last 2 versions
sass:
  style: compressed
  load_paths:
    - _sass
    - ../node_modules

collections:
  pages:
    output: true
    permalink: /:path
  reviews:
    output: false
    
# Include
include:
  - _redirects

# Exclude
# exclude:
#   - 'package.json'
#   - 'Gemfile'
#   - '*.gemspec'
#   - '*.lock'
