# site settings
title: Better Way Pest Control
email: bbodine1@gmail.com
email-cc: bbodine1@gmail.com
description: >-
  Pest Control Services for Hartselle, Decatur, Athens, Madison.
  We have the best pest solutions and the best prices to protect the things
  you love from pests.
reviewlimit: 5
gtm-id: MR2CTVP
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# General data
logo-dark: /img/main-logo-dark.png
logo-light: /img/main-logo-light.png
street: 209 Sparkman St SW
city: Hartselle
state: AL
zipcode: 35640
phone: '(256) 580-6181'
service-area: 'North Alabama including Hartselle, Decatur, Madison, Athens, and Moulton'


# Social links
facebook: https://www.facebook.com/BetterWayPestControl/
google: https://goo.gl/maps/c3yoeyEDwTn
yelp: https://www.yelp.com/biz/better-way-pest-control-hartselle


# Work Hours
work-hours:
  - day: Sunday
    hours: Closed
  - day: Monday
    hours: 7am - 6pm
  - day: Tuesday
    hours: 7am - 6pm
  - day: Wednesday
    hours: 7am - 6pm
  - day: Thursday
    hours: 7am - 6pm
  - day: Friday
    hours: 7am - 6pm
  - day: Saturday
    hours: 7am - 6pm


# Facebook Share Meta
share-website: https://betterwaypestcontrol.com
share-title: Better Pest Control for North Alabama
share-description: >-
  Our company strives to provide our customers with a great
  service at an affordable price, while protecting your home
  and family from unwanted pests.
share-image: share.jpg


# Navigation
nav:
  - title: Home
    url: /
    subpages:

  - title: About
    url: /about
    subpages:

  - title: Services
    url: /services
    subpages:
      - title: Residential & Commercial Pest Control
        url: /services/residential-commercial
      - title: Mosquito Control
        url: /services/mosquito
      - title: Rodent Control
        url: /services/rodents
      - title: Brown Recluse Control
        url: /services/brown-recluse

  - title: Payments
    url: /payments
    subpages:


# PayPal settings
paypal-email: israel@betterwaypestcontrol.com
paypal-amount-onform: true
paypal-allow-cancel: false
paypal-sandbox: true
paypal-sandbox-email: bbodine1+merchant@gmail.com


# build settings
source: src
destination: dist
markdown: kramdown

plugins:
  - jekyll-autoprefixer
  - jekyll-sitemap

autoprefixer:
  browsers:
    - last 2 versions
sass:
  style: compressed
  load_paths:
    - _sass
    - ../node_modules

collections:
  pages:
    output: true
    permalink: /:path
  reviews:
    output: false
    
# Include
# include:
#   - _pages
#   - _reviews

# Exclude
# exclude:
#   - 'package.json'
#   - 'Gemfile'
#   - '*.gemspec'
#   - '*.lock'
